Update check-urls.yml

diff --git a/.github/workflows/check-urls.yml b/.github/workflows/check-urls.yml
--- a/.github/workflows/check-urls.yml
+++ b/.github/workflows/check-urls.yml
@@ -5,36 +5,29 @@ on:
   pull_request:
 
 permissions:
-  # needed for checkout code
   contents: read
 
-# This allows a subsequently queued workflow run to interrupt/wait for previous runs
 concurrency:
   group: '${{ github.workflow }} @ ${{ github.run_id }}'
-  cancel-in-progress: false         # true = interrupt, false = wait
+  cancel-in-progress: false
 
 jobs:
 
-# NOTE: tj-actions/changed-files.
-# For push events you need to include fetch-depth: 0 | 2 depending on your use case.
-#  0: retrieve all history for all branches and tags
-#  1: retrieve only current commit (by default)
-#  2: retrieve until the preceding commit
   get-changed-files:
     name: Get changed files
     runs-on: ubuntu-latest
     outputs:
       fetch-depth: ${{ steps.set-params.outputs.fetch-depth }}
-      files:       ${{ steps.set-files.outputs.files }}
-      files-len:   ${{ steps.set-files.outputs.files-len }}
-      matrix:      ${{ steps.set-matrix.outputs.matrix }}
+      files: ${{ steps.set-files.outputs.files }}
+      files-len: ${{ steps.set-files.outputs.files-len }}
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
     steps:
       - name: Determine workflow params
         id: set-params
         run: |
           echo "fetch_depth=0" >> $GITHUB_OUTPUT
           if [ "${{ github.event_name }}" == "pull_request" ]; then
-            echo "fetch_depth=0" >> $GITHUB_OUTPUT
+            echo "fetch-depth=0" >> $GITHUB_OUTPUT
           fi
       - name: Checkout
         uses: actions/checkout@v4
@@ -48,20 +41,11 @@ jobs:
           json: true
       - id: set-files
         run: |
-          echo "${{ steps.changed-files.outputs.all_changed_files }}"  \
-            | jq --raw-output '. | join(" ")'  \
-            | sed -e 's/^/files=/'  \
-            >> $GITHUB_OUTPUT
-          echo "${{ steps.changed-files.outputs.all_changed_files }}"  \
-            | jq --raw-output '. | length'  \
-            | sed -e 's/^/files-len=/'  \
-            >> $GITHUB_OUTPUT
+          echo "${{ steps.changed-files.outputs.all_changed_files }}" | jq --raw-output '. | join(" ")' | sed -e 's/^/files=/' >> $GITHUB_OUTPUT
+          echo "${{ steps.changed-files.outputs.all_changed_files }}" | jq --raw-output '. | length' | sed -e 's/^/files-len=/' >> $GITHUB_OUTPUT
       - id: set-matrix
         run: |
-          echo "{\"file\":${{ steps.changed-files.outputs.all_changed_files }}}"  \
-            | sed -e 's/^/matrix=/'  \
-            >> $GITHUB_OUTPUT
-
+          echo "{\"file\":${{ steps.changed-files.outputs.all_changed_files }}}" | sed -e 's/^/matrix=/' >> $GITHUB_OUTPUT
 
   check-urls:
     name: Check @ ${{ matrix.file }}
@@ -82,28 +66,28 @@ jobs:
         with:
           ruby-version: 2.6
       - name: Install awesome_bot
-        run: |
-          gem install awesome_bot
+        run: gem install awesome_bot
       - name: Set output
         id: set-output
         run: echo "FILENAME=$(echo ${{ matrix.file }} | grep -oE '[a-zA-Z0-9_-]+(\.yml|\.md)')" >> "$GITHUB_OUTPUT"
       - name: "Check URLs of file: ${{ matrix.file }}"
         run: |
-          awesome_bot "${{ matrix.file }}" --allow-redirect --allow-dupe --allow-ssl || true;
+          awesome_bot "${{ matrix.file }}" --allow-redirect --allow-dupe --allow-ssl --output-format json > ab-results-${{ steps.set-output.outputs.FILENAME}}.json
+          if [ $? -ne 0 ]; then
+            echo "Error checking URLs in ${{ matrix.file }}" >> $GITHUB_STEP_SUMMARY
+          fi
       - uses: actions/upload-artifact@v4
         with:
           name: ${{ steps.set-output.outputs.FILENAME}}
           path: ${{ github.workspace }}/ab-results-*.json
-
 
   reporter:
     name: GitHub report
     needs: [get-changed-files, check-urls]
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout  # for having the sources of the local action
+      - name: Checkout
         uses: actions/checkout@v4
-        # download and unzip the ab-results-*.json generated by job-matrix: check-urls
       - uses: actions/download-artifact@v3
         with:
           name: ${{ steps.set-output.outputs.FILENAME}}
@@ -113,4 +97,4 @@ jobs:
           ab-root: ${{ github.workspace }}
           files: ${{ needs.get-changed-files.outputs.files }}
           separator: " "
-          append-heading: ${{ true }}
+          append-heading: true
